-- CreateTable
CREATE TABLE "public"."StudentContextDocument" (
    "studentEmail" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "isAutoGenerated" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "StudentContextDocument_pkey" PRIMARY KEY ("studentEmail")
);

-- AddForeignKey
ALTER TABLE "public"."StudentContextDocument" ADD CONSTRAINT "StudentContextDocument_studentEmail_fkey" FOREIGN KEY ("studentEmail") REFERENCES "public"."Student"("email") ON DELETE CASCADE ON UPDATE CASCADE;
