'use server';

import { cookies } from 'next/headers';
import prisma from '../../lib/prisma';
import { ensureStudentContextDocument } from '../../lib/studentContext';

type ActionError = { error: string };
type ActionSuccess = { success: string };

type SaveState = ActionError | ActionSuccess | void;
type RegenerateState = ActionError | (ActionSuccess & { content?: string | null }) | void;

type StudentWithContext = NonNullable<
  Awaited<
    ReturnType<typeof prisma.student.findUnique>
  >
>;

type LoadResult = {
  content: string;
  student: StudentWithContext;
};

function getSessionEmail(): string | null {
  const sessionCookie = cookies().get('withstady-session');
  if (!sessionCookie?.value) return null;

  try {
    const parsed = JSON.parse(sessionCookie.value) as { email?: unknown };
    if (typeof parsed?.email === 'string' && parsed.email.trim()) {
      return parsed.email.trim().toLowerCase();
    }
  } catch (error) {
    return null;
  }

  return null;
}

export async function loadContextDocument(): Promise<LoadResult> {
  const email = getSessionEmail();
  if (!email) {
    throw new Error('ログインが必要です。');
  }

  const student = await prisma.student.findUnique({
    where: { email },
    include: { contextDocument: true }
  });

  if (!student) {
    throw new Error('ログインが必要です。');
  }

  const content = await ensureStudentContextDocument(student);

  return {
    content: content || '',
    student
  };
}

export async function saveContextDocumentAction(prevState: unknown, formData: FormData): Promise<SaveState> {
  const email = getSessionEmail();

  if (!email) {
    return { error: 'ログインが必要です。' };
  }

  const rawContent = formData.get('content');
  const content = typeof rawContent === 'string' ? rawContent : '';

  await prisma.studentContextDocument.upsert({
    where: { studentEmail: email },
    create: {
      studentEmail: email,
      content,
      isAutoGenerated: false
    },
    update: {
      content,
      isAutoGenerated: false
    }
  });

  return { success: 'パーソナライズドドキュメントを保存しました。' };
}

export async function regenerateContextDocumentAction(): Promise<RegenerateState> {
  const email = getSessionEmail();

  if (!email) {
    return { error: 'ログインが必要です。' };
  }

  const student = await prisma.student.findUnique({
    where: { email },
    include: { contextDocument: true }
  });

  if (!student) {
    return { error: '学習者情報が見つかりません。' };
  }

  const content = await ensureStudentContextDocument(student, { forceRegenerate: true });

  return { success: '最新のプロフィール情報から再生成しました。', content };
}
